### PR TITLE
Preparing for MariaDB 10.3

### PR DESCRIPTION
**Pull request by iangilfillan**

### CODE REVIEW

**Comment by iangilfillan** [comment]
What sort of problems have there been in the past? If 10.3 works, the positive to listing it is that one will be able to test 10.3 as soon as it is released. If 10.3 doesn't work, it will not work in spite of the 10.3 listing rather than just due to it. Is there any other downside?

**Comment by datacharmer** [comment]
Usually, every major release requires some changes before it can work. This is because there are new defaults, or installation procedure changes, or both.
Making the version "supported" is not good if it then fails for some hard to tell reason. I'd rather add the version when there is something to test, and it has been proved that the installation works.

**Comment by iangilfillan** [comment]
I have removed 10.3 from the list of supported versions, so the pull request just contains the fixes/clarifications to the README.

**Comment by datacharmer** [comment]
I forgot to mention something: the README file is created dynamically from lib/MySQL/Sandbox.pm 
I have applied some of the corrections that you have suggested, although I reduced the number of mentions of MariaDB in the text. Repeating it at almost every occurrence of "MySQL" does not improve clarity. The corrections will show up in the next release. I won't publish one just for a change in the README, though.
Thanks for your contribution.

**Pull request merged**
